### PR TITLE
Intrinisicfy AddOverflow

### PR DESCRIPTION
**Pull request by benaadams**
Missed this one

### CODE REVIEW

**Review by tanishqjasoria — APPROVED** [review]

**Review by LukaszRozmej — APPROVED** [review]

**Review by rubo — CHANGES_REQUESTED** [review]
Could you please revert the changes to GitHub Actions workflows?

**Comment by benaadams** [comment]
> Could you please revert the changes to GitHub Actions workflows?

Done, but then doesn't seem to test anything?

**Comment by rubo** [comment]
> Done, but then doesn't seem to test anything?

Yep, that's now fixed. Next time it will trigger. Thank you.

**Review by rubo — APPROVED** [review]
Tests passed

**Comment by benaadams** [comment]
> Tests passed

Also needs a variant with the env var
```
env:
  DOTNET_EnableHWIntrinsic: 0
```
To test the non intrinsic path

**Comment by rubo** [comment]
@benaadams I checked the usage of that previously and it's referenced in the benchmarks project only. How does this work in tests?

**Comment by benaadams** [comment]
> @benaadams I checked the usage of that previously and it's referenced in the benchmarks project only. How does this work in tests?

Check `run-tests-nointrinsics.yml` in reverted https://github.com/NethermindEth/int256/pull/28/commits/16252b1a9650e17fe19f950b2a4d40fc942f4890

**Comment by rubo** [comment]
> Check run-tests-nointrinsics.yml in reverted https://github.com/NethermindEth/int256/commit/16252b1a9650e17fe19f950b2a4d40fc942f4890

Right, but that variable is used in the benchmarks project while the workflow runs the tests project only. Did I miss something?

**Comment by benaadams** [comment]
> > Check run-tests-nointrinsics.yml in reverted [16252b1](https://github.com/NethermindEth/int256/commit/16252b1a9650e17fe19f950b2a4d40fc942f4890)
> 
> Right, but that variable is used in the benchmarks project while the workflow runs the tests project only. Did I miss something?

Benchmark is to test intrinsics vs non-intrinsics for speed (it creates new exes for each test case)

Tests is to make sure both the intrinsics and non-intrinsics produce the same results; so the tests need to be run twice, once with the env variable set and once without it

**Comment by rubo** [comment]
I see, so the idea is to run tests twice with intrinsics on/off. Two things:

1. How do tests handle that environment variable? I don't see any reference to it in the code. It's a custom variable introduced by you, so I presume there should be a reference to it in the tests' code, correct?
2. If they do process it somehow, I will update the workflow to run correctly as in the PR tests run twice for `debug` and `release` with the variable always set to `0`.

**Comment by benaadams** [comment]
> 1. How do tests handle that environment variable? I don't see any reference to it in the code. It's a custom variable introduced by you, so I presume there should be a reference to it in the tests' code, correct?

Is a runtime switch used by the Jit; so if its set before program startup the Jit won't generate any SSE/AVX/etc code; can also go more fine grained if desired and switch off individual feature sets [dotnet/runtime/src/coreclr/jit/jitconfigvalues.h#L315-L353](https://github.com/dotnet/runtime/blob/85533759a4119c39068dbb211cd297cee3733496/src/coreclr/jit/jitconfigvalues.h#L315-L353)

> 2. If they do process it somehow, I will update the workflow to run correctly as in the PR tests run twice for `debug` and `release` with the variable always set to `0`.

Needs to be set to `0` and `1`; so it can test both paths

**Comment by rubo** [comment]
@benaadams Oh, thanks for the link. I was looking for this a few days ago with no luck but I was doing that with `DOTNET_` prefix. Will update our workflow then.

**Comment by benaadams** [comment]
> @benaadams Oh, thanks for the link. I was looking for this a few days ago with no luck but I was doing that with `DOTNET_` prefix. Will update our workflow then.

This should work? https://github.com/NethermindEth/int256/pull/30

**Comment by rubo** [comment]
@benaadams Merged, thank you!

**Pull request merged**
